name: eddiv2
version: 0.0.1
description: eddiv2
repository: https://github.com/val314159/eddiv2
scripts:
  pkg: ./scripts/yaml2json
  test: npm run compile && open http://127.0.0.1:9090/index.html
  compile: sh scripts/compile.sh
  clean: sh scripts/clean.sh
  open: open index.html
dependencies:
  eel-parser:   ">0.0.1"
  eel-compiler: ">0.0.1"
license: MIT
